version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1-node

    env:
      GO111MODULE: "on"

    steps:
      - checkout
      - run: cd frontend && yarn install --offline
      - run: make format
      - run: make build
      - run: git diff --exit-code
      - persist_to_workspace:
          root: .
          paths:
          - crochet

  push_image:
    docker:
    - image: circleci/golang

    steps:
    - checkout
    - setup_remote_docker
    - attach_workspace:
        at: .
    - run: docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD quay.io
    - run: docker build -t quay.io/simonpasquier/crochet:latest .
    - run: docker push quay.io/simonpasquier/crochet

workflows:
  version: 2
  main:
    jobs:
    - build:
        filters:
          tags:
            only: /.*/
    - push_image:
        context: Quay
        requires:
        - build
        filters:
          branches:
            only: master
