version: 2.1

orbs:
  go: circleci/go@0.2.0

jobs:
  build:
    docker:
    - image: circleci/golang:1-node

    steps:
      - checkout
      - go/load-cache:
          key: v1
      - restore_cache:
          keys:
          - v1-npm-deps-{{ checksum "frontend/yarn.lock" }}
          - v1-npm-deps-
      - run: cd frontend && yarn install
      - run: make format
      - run: make build
      - persist_to_workspace:
          root: .
          paths:
          - crochet
      - go/save-cache:
          key: v1
      - save_cache:
          key: v1-npm-deps-{{ checksum "frontend/yarn.lock" }}
          paths:
          - /home/circleci/.cache/yarn

  push_image:
    docker:
    - image: circleci/golang

    steps:
    - checkout
    - setup_remote_docker
    - attach_workspace:
        at: .
    - run: docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD quay.io
    - run: docker build -t quay.io/simonpasquier/crochet:latest .
    - run: docker push quay.io/simonpasquier/crochet

workflows:
  version: 2
  main:
    jobs:
    - build:
        filters:
          tags:
            only: /.*/
    - push_image:
        context: Quay
        requires:
        - build
        filters:
          branches:
            only: master
